"""Deterministic tests for full/filtered diff artifact construction."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from review_bot.diff_filter import (
    DiffFilterError,
    GitBlobReader,
    classify_marker,
    classify_metadata,
    split_diff_sections,
    write_diff_artifacts,
)


def _patch(path: str, added: str = "value = 1", *, trailing_newline: bool = True) -> str:
    text = (
        f"diff --git a/{path} b/{path}\n"
        "index 1111111..2222222 100644\n"
        f"--- a/{path}\n"
        f"+++ b/{path}\n"
        "@@ -0,0 +1 @@\n"
        f"+{added}"
    )
    return text + ("\n" if trailing_newline else "")


class FakeBlobReader:
    def __init__(self, content: dict[str, tuple[bytes, ...] | None] | None = None):
        self.content = content or {}
        self.calls: list[tuple[str, int]] = []

    def first_nonblank_lines(self, path: str, limit: int = 20) -> tuple[bytes, ...] | None:
        self.calls.append((path, limit))
        return self.content.get(path, ())


def test_split_diff_sections_preserves_exact_order_and_text():
    first = _patch("src/a.py")
    second = _patch("src/b.py", trailing_newline=False)
    sections = split_diff_sections(first + second)
    assert [(section.path, section.text) for section in sections] == [
        ("src/a.py", first),
        ("src/b.py", second),
    ]


def test_split_diff_sections_supports_quoted_paths():
    text = (
        'diff --git "a/docs/with space.md" "b/docs/with space.md"\n'
        "index 1111111..2222222 100644\n"
        '--- "a/docs/with space.md"\n'
        '+++ "b/docs/with space.md"\n'
        "@@ -0,0 +1 @@\n"
        "+content\n"
    )
    sections = split_diff_sections(text)
    assert sections[0].path == "docs/with space.md"
    assert sections[0].text == text


@pytest.mark.parametrize("text", ["unexpected\n", "preamble\n" + _patch("src/a.py")])
def test_split_diff_sections_fails_closed_on_unattributable_content(text: str):
    with pytest.raises(DiffFilterError, match="provider diff"):
        split_diff_sections(text)


@pytest.mark.parametrize(
    ("path", "category", "rule"),
    [
        ("uv.lock", "lockfile", "lockfile-basename:uv.lock"),
        ("vendor/uv.lock", "lockfile", "lockfile-basename:uv.lock"),
        (r"src\\vendor\\client.py", "vendored", "vendored-path-segment:vendor"),
        ("src/third-party/client.py", "vendored", "vendored-path-segment:third-party"),
        ("web/dist/app.js", "generated", "generated-path-segment:dist"),
        ("proto/message_pb2.py", "generated", "generated-filename:*_pb2.py"),
        ("web/app.min.css", "generated", "generated-filename:*.min.css"),
    ],
)
def test_classify_metadata_uses_fixed_precedence_and_rules(path: str, category: str, rule: str):
    exclusion = classify_metadata(path)
    assert exclusion is not None
    assert exclusion.path == path
    assert exclusion.category == category
    assert exclusion.rule == rule


@pytest.mark.parametrize(
    "path",
    [
        "UV.lock",
        "uv.lock.py",
        "src/vendor_api/client.py",
        "src/Vendor/client.py",
        "web/Dist/app.js",
        "web/app.MIN.js",
        "src/mapping.py",
    ],
)
def test_classify_metadata_is_exact_and_case_sensitive(path: str):
    assert classify_metadata(path) is None


def test_marker_classification_is_case_insensitive_and_ordered():
    at_generated = classify_marker("src/client.py", (b"# @Generated by tool",))
    do_not_edit = classify_marker("src/client.py", (b"// GENERATED - Do Not Edit",))
    assert at_generated is not None
    assert at_generated.rule == "generated-marker:@generated"
    assert do_not_edit is not None
    assert do_not_edit.rule == "generated-marker:generated+do-not-edit"


def test_marker_after_first_twenty_nonblank_lines_is_not_classified():
    lines = tuple([b"ordinary"] * 20 + [b"@generated"])
    assert classify_marker("src/client.py", lines) is None


def test_write_diff_artifacts_preserves_full_diff_and_records_exclusions(tmp_path: Path):
    provider = _patch("src/main.py") + _patch("vendor/client.py") + _patch("src/api.py")
    reader = FakeBlobReader({"src/api.py": (b"# @generated",)})

    artifacts = write_diff_artifacts(tmp_path, provider, blob_reader=reader)  # type: ignore[arg-type]

    assert artifacts.provider_diff.read_text() == provider
    assert artifacts.review_diff.read_text() == _patch("src/main.py")
    assert json.loads(artifacts.filter_manifest.read_text()) == {
        "version": 1,
        "exclusions": [
            {
                "path": "vendor/client.py",
                "category": "vendored",
                "rule": "vendored-path-segment:vendor",
            },
            {
                "path": "src/api.py",
                "category": "generated",
                "rule": "generated-marker:@generated",
            },
        ],
    }
    assert reader.calls == [("src/main.py", 20), ("src/api.py", 20)]


def test_every_filtered_file_produces_empty_review_diff_deterministically(tmp_path: Path):
    provider = _patch("uv.lock") + _patch("node_modules/pkg/index.js")
    reader = FakeBlobReader()
    first = write_diff_artifacts(tmp_path, provider, blob_reader=reader)  # type: ignore[arg-type]
    first_manifest = first.filter_manifest.read_bytes()
    second = write_diff_artifacts(tmp_path, provider, blob_reader=reader)  # type: ignore[arg-type]
    assert first.review_diff.read_text() == ""
    assert second.filter_manifest.read_bytes() == first_manifest
    assert reader.calls == []


def test_mixed_diff_forms_remain_complete_sections(tmp_path: Path):
    new_file = (
        "diff --git a/new.py b/new.py\n"
        "new file mode 100644\n"
        "index 0000000..2222222\n"
        "--- /dev/null\n"
        "+++ b/new.py\n"
        "@@ -0,0 +1 @@\n"
        "+new\n"
    )
    renamed = (
        "diff --git a/old.py b/new.py\n"
        "similarity index 100%\n"
        "rename from old.py\n"
        "rename to new.py\n"
    )
    deleted = (
        "diff --git a/deleted.py b/deleted.py\n"
        "deleted file mode 100644\n"
        "index 1111111..0000000\n"
        "--- a/deleted.py\n"
        "+++ /dev/null\n"
        "@@ -1 +0,0 @@\n"
        "-old\n"
    )
    binary = (
        "diff --git a/logo.png b/logo.png\n"
        "index 1111111..2222222 100644\n"
        "Binary files a/logo.png and b/logo.png differ\n"
    )
    provider = (
        new_file
        + renamed
        + deleted
        + binary
        + _patch("generated/client.py", trailing_newline=False)
    )
    artifacts = write_diff_artifacts(
        tmp_path,
        provider,
        blob_reader=FakeBlobReader(),  # type: ignore[arg-type]
    )
    assert artifacts.review_diff.read_text() == new_file + renamed + deleted + binary
    assert artifacts.exclusions[0].path == "generated/client.py"


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)


def test_git_blob_reader_reads_head_blob_not_worktree_symlink(tmp_path: Path):
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    _git(repo, "config", "user.name", "test")
    _git(repo, "config", "user.email", "test@example.com")
    target = repo / "client.py"
    target.write_text("# @generated\n")
    _git(repo, "add", "client.py")
    _git(repo, "commit", "-m", "fixture")

    target.unlink()
    outside = tmp_path / "outside.py"
    outside.write_text("ordinary\n")
    target.symlink_to(outside)

    assert GitBlobReader(repo).first_nonblank_lines("client.py") == (b"# @generated",)


def test_git_blob_reader_does_not_inspect_committed_symlink(tmp_path: Path):
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    _git(repo, "config", "user.name", "test")
    _git(repo, "config", "user.email", "test@example.com")
    (repo / "target.py").write_text("# @generated\n")
    (repo / "link.py").symlink_to("target.py")
    _git(repo, "add", "target.py", "link.py")
    _git(repo, "commit", "-m", "fixture")

    assert GitBlobReader(repo).first_nonblank_lines("link.py") is None


def test_git_blob_reader_does_not_inspect_gitlink(tmp_path: Path):
    child = tmp_path / "child"
    child.mkdir()
    _git(child, "init")
    _git(child, "config", "user.name", "test")
    _git(child, "config", "user.email", "test@example.com")
    (child / "README.md").write_text("child\n")
    _git(child, "add", "README.md")
    _git(child, "commit", "-m", "child")
    child_sha = _git(child, "rev-parse", "HEAD").stdout.strip()

    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    _git(repo, "config", "user.name", "test")
    _git(repo, "config", "user.email", "test@example.com")
    _git(repo, "update-index", "--add", "--cacheinfo", f"160000,{child_sha},submodule")
    _git(repo, "commit", "-m", "gitlink")

    assert GitBlobReader(repo).first_nonblank_lines("submodule") is None


def test_blob_read_failure_stops_artifact_construction(tmp_path: Path):
    class BrokenReader:
        def first_nonblank_lines(self, path: str, limit: int = 20):
            raise DiffFilterError(f"could not read {path}")

    with pytest.raises(DiffFilterError, match="could not read src/main.py"):
        write_diff_artifacts(
            tmp_path,
            _patch("src/main.py"),
            blob_reader=BrokenReader(),  # type: ignore[arg-type]
        )
    assert not (tmp_path / "provider-diff.diff").exists()
